### ISSUE TITLE
Crashes node-RED on ubuntu

### ISSUE THREAD

**Issue by Paul-Reed** [bartbutenaers/node-red-contrib-process-resources#1]
Hi Bart, sorry to spoil your weekend!

Using Node-RED version: v3.0.2, Node.js  version: v16.19.1 on a Oracle Cloud instance running Ubuntu v20.04.
Using a simple 3 node flow; inject - your node -debug, whenever I run the flow it crashes node-RED.
In the node-RED log (debug), it appears to crash following -
`25 Mar 13:23:31 - [error] TypeError: Cannot read properties of null (reading 'memory')` if the node is set to Memory. OR
`25 Mar 13:21:19 - [error] TypeError: Cannot read properties of null (reading 'cpu')` if the node is set to cpu

The full log is pasted below;
```
25 Mar 13:21:19 - [error] TypeError: Cannot read properties of null (reading 'cpu')
    at /home/ubuntu/.node-red/node_modules/node-red-contrib-process-resources/process_resources.js:50:44
    at Array.sort (<anonymous>)
    at sendMessage (/home/ubuntu/.node-red/node_modules/node-red-contrib-process-resources/process_resources.js:47:33)
    at /home/ubuntu/.node-red/node_modules/node-red-contrib-process-resources/process_resources.js:113:25
    at /home/ubuntu/.node-red/node_modules/pidusage/lib/stats.js:90:7
    at each (/home/ubuntu/.node-red/node_modules/pidusage/lib/helpers/parallel.js:24:15)
    at /home/ubuntu/.node-red/node_modules/pidusage/lib/helpers/parallel.js:32:9
    at /home/ubuntu/.node-red/node_modules/pidusage/lib/procfile.js:111:14
    at /home/ubuntu/.node-red/node_modules/pidusage/lib/procfile.js:43:5
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 9.744s CPU time.
nodered.service: Scheduled restart job, restart counter is at 1.
Stopped Node-RED graphical event wiring tool.
nodered.service: Consumed 9.744s CPU time.
Started Node-RED graphical event wiring tool.
25 Mar 13:21:40 - [info]
Welcome to Node-RED
===================
```

**Comment by bartbutenaers** [comment]
Hi @Paul-Reed,

When I told you yesterday that we should do some fun stuff together, I had not something like this in mind ;-)

Yes it was all asynchronous processing in this node, so the exceptions are not intercepted by the try-catch mechanisme.  So I have rewritten this node, in the master branch of this repo.  

But then I am still not sure why you arrived at that exception.  I tried a bunch of different things, but could not reproduce it.

Would be nice if you could install the node from this repo, and let me know whether your exception still occurs.

Bart

**Comment by Paul-Reed** [comment]
That has stopped node-RED crashing, but still getting the error;
`25 Mar 22:55:31 - [error] [process-resources:16ef12632bf16ef2] TypeError: Cannot read properties of null (reading 'cpu')`  AND
`25 Mar 23:00:03 - [error] [process-resources:16ef12632bf16ef2] TypeError: Cannot read properties of null (reading 'memory')`

This is a new install in a new oracle cloud account, and this is the only flow in node-RED.
I'm using it to monitor CPU & Memory, as Oracle reclaim accounts if the fall below usage levels.

![oracle](https://user-images.githubusercontent.com/973580/227746721-85870d70-af7f-42da-b5c2-e2059f07a935.JPG)

**Comment by bartbutenaers** [comment]
Yes I was afraid that your problem wouldn't be solved.
The problem is that I use two npm libraries under the cover, and I have no idea which one is giving me unexpected data on Oracle cloud platform.

I have refactored the code again, and I now have added some extra logging:

![image](https://user-images.githubusercontent.com/14224149/227759481-44335738-28b6-4491-af89-b9790cbf1f44.png)

Can you tell me what is being logged in your case?
Unless you can debug this code yourself, I don't see another way to troubleshoot this...

**Comment by Paul-Reed** [comment]
I get...

![error](https://user-images.githubusercontent.com/973580/227764396-6fe16c07-15ea-4f7a-ba84-43f370864bd9.JPG)

The same log as above pasted as text...

```
childProcessIds = [11089,11062,11068,11067,11066,11065,11064,11063]
childProcessesStats = {"11062":{"cpu":0,"memory":1019904,"ctime":0,"elapsed":386960,"timestamp":1679819174299,"pid":11062,"ppid":11031},"11063":{"cpu":0,"memory":196608,"ctime":50790,"elapsed":386960,"timestamp":1679819174299,"pid":11063,"ppid":11062},"11064":{"cpu":0,"memory":196608,"ctime":51010,"elapsed":386960,"timestamp":1679819174299,"pid":11064,"ppid":11062},"11065":{"cpu":0,"memory":196608,"ctime":51930,"elapsed":386960,"timestamp":1679819174299,"pid":11065,"ppid":11062},"11066":{"cpu":0,"memory":196608,"ctime":51360,"elapsed":386960,"timestamp":1679819174299,"pid":11066,"ppid":11062},"11067":{"cpu":0,"memory":196608,"ctime":130,"elapsed":386960,"timestamp":1679819174299,"pid":11067,"ppid":11062},"11068":{"cpu":0,"memory":2148155392,"ctime":3760,"elapsed":386960,"timestamp":1679819174299,"pid":11068,"ppid":11062},"11089":null}
26 Mar 08:26:14 - [error] [process-resources:16ef12632bf16ef2] TypeError: Cannot read properties of null (reading 'memory')
```

**Comment by Paul-Reed** [comment]
Just looking at the running processes - `childProcessIds = [11089,11062,11068,11067,11066,11065,11064,11063]` and all of them except `11089` relate to a script that I'm running 24/7.
If I stop that script, and run your node, I just get `childProcessIds = [11305]` in the log, and your node then works OK, and produces the expected data.
But for some reason, whenever I resume the script, your node no longer works works! so it seems to be a bad interaction between the two.

I'm using an exec node to keep the script running.

**Comment by bartbutenaers** [comment]
I am not at my computer now, but I see that the statistics for one of the processes is undefined:
`"11089":null`
Is that the process you are talking about?

For some reason the [pidusage](https://www.npmjs.com/package/pidusage) npm library doesn't give statiscs for that pid.  I don't see any open [issues](https://github.com/soyuka/pidusage/issues) about this.

**Comment by bartbutenaers** [comment]
I could easily skip those from my result, but I am wondering if my result is then still complete.  Could you check if that pid is still active after you get the error?

**Comment by Paul-Reed** [comment]
After a restart of the script, the offending PID = 11745.
Checking `ps aux` both **before** and **after** running your node, there is no entry for PID 11745 ???

![error](https://user-images.githubusercontent.com/973580/227769048-88857f63-1748-4c80-9a6e-c1da9738edf8.JPG)

EDIT - I can access the stats via an Oracle dashboard, so I can check if the calculations are correct or not,

**Comment by Paul-Reed** [comment]
Hi Bart, this appears to be an issue related to the script that I'm running, so I'm likely to be the only person hitting this problem.
For my use, I'm just finishing a (another) bash script that returns The CPU & Memory usage, so I can use that instead.

Do you want to close this issue?

**Comment by bartbutenaers** [comment]
Hey Paul,

I have added a fix to skip child PID's with statistics ***null***, because I can't do anything with those PID's anyway.
Could you test that.

Of course it would be better to analyze why these child PID's have null statistics.
But creating an Oracle cloud account and debugging the pidusage library code, is unfortunately not possible anymore in my limited free time.

**Comment by Paul-Reed** [comment]
Tried it, but the `cpu usage %` shows zero, when it is actually about 11%.
There is nothing showing in the node-RED log.

![cpu](https://user-images.githubusercontent.com/973580/227798014-45440c9c-475c-4015-8637-894effbb57b2.JPG)

Nobody else has raised this, and it's obviously an edge case, so please don't spend any more of your time on it.

**Comment by bartbutenaers** [comment]
Well unfortunately I see in your feedback above that the "cpu" value for every child process is 0:
```
childProcessesStats = {"11062":{"cpu":0,"memory":1019904,"ctime":0,"elapsed":386960,"timestamp":1679819174299,"pid":11062,"ppid":11031},"11063":{"cpu":0,"memory":196608,"ctime":50790,"elapsed":386960,"timestamp":1679819174299,"pid":11063,"ppid":11062},"11064":{"cpu":0,"memory":196608,"ctime":51010,"elapsed":386960,"timestamp":1679819174299,"pid":11064,"ppid":11062},"11065":{"cpu":0,"memory":196608,"ctime":51930,"elapsed":386960,"timestamp":1679819174299,"pid":11065,"ppid":11062},"11066":{"cpu":0,"memory":196608,"ctime":51360,"elapsed":386960,"timestamp":1679819174299,"pid":11066,"ppid":11062},"11067":{"cpu":0,"memory":196608,"ctime":130,"elapsed":386960,"timestamp":1679819174299,"pid":11067,"ppid":11062},"11068":{"cpu":0,"memory":2148155392,"ctime":3760,"elapsed":386960,"timestamp":1679819174299,"pid":11068,"ppid":11062},"11089":null}
```
So there must be a bug in the [pidusage](https://github.com/soyuka/pidusage) library.  If you want, we can create an issue in that repo.  I need to publish a new version for my node anyway, because my master branch now contains quite a lot of changes...

**Comment by Paul-Reed** [comment]
_"So there must be a bug in the [pidusage](https://github.com/soyuka/pidusage) library. If you want, we can create an issue in that repo."_

I've raised an issue - https://github.com/soyuka/pidusage/issues/169
Feel free to contribute to the issue if you wish.

**Comment by bartbutenaers** [comment]
Thanks for creating the issue!
If you can share your test account with them, I would mention that (that you can share your credentials) so they know they can easily test this...

**Comment by Paul-Reed** [comment]
Hhmm, I'm not sure about sharing access with them, as it's not a test account, and especially as I've spent most of today moving flows into the server.

**Comment by bartbutenaers** [comment]
Ah ok, I now see I heve not interpreted you correctly.  Thought you had setup a new test account for this issue.  Forget what I said!!!

**Comment by cameo69** [comment]
Hi, I had a similar issue, reported here: https://discourse.nodered.org/t/node-red-kept-restarting-upon-git-push/77181

```
3 Apr 08:06:09 - [red] Uncaught Exception:
3 Apr 08:06:09 - [error] TypeError: Cannot read properties of null (reading 'cpu')
    at /data/node_modules/node-red-contrib-process-resources/process_resources.js:61:75
    at Array.forEach (<anonymous>)
    at sendMessage (/data/node_modules/node-red-contrib-process-resources/process_resources.js:59:33)
    at /data/node_modules/node-red-contrib-process-resources/process_resources.js:113:25
    at /data/node_modules/pidusage/lib/stats.js:90:7
    at each (/data/node_modules/pidusage/lib/helpers/parallel.js:24:15)
    at /data/node_modules/pidusage/lib/helpers/parallel.js:32:9
    at /data/node_modules/pidusage/lib/procfile.js:111:14
    at /data/node_modules/pidusage/lib/procfile.js:43:5
    at FSReqCallback.wrapper [as oncomplete] (node:fs:660:5)
3 Apr 08:06:12 - [info] 
Welcome to Node-RED
===================
3 Apr 08:06:12 - [info] Node-RED version: v3.0.2
3 Apr 08:06:12 - [info] Node.js  version: v16.16.0
3 Apr 08:06:12 - [info] Linux 5.10.60-qnap x64 LE
3 Apr 08:06:13 - [info] Loading palette nodes
3 Apr 08:06:13 - [info] Node-RED FlexDash plugin version 0.4.154
3 Apr 08:06:13 - [info] Node-RED Vue version 0.1.15
3 Apr 08:06:14 - [info] Creating Vue template for 'flexdash dashboard' from /data/node_modules/@flexdash/node-red-flexdash/flexdash-dashboard.vue
3 Apr 08:06:14 - [info] Node-RED FlexDash version 0.4.154
3 Apr 08:06:14 - [info] Node-RED FD Core Widgets version 0.4.64
3 Apr 08:06:14 - [info] Creating Vue template for 'flexdash container' from /data/node_modules/@flexdash/node-red-flexdash/flexdash-container.vue
3 Apr 08:06:14 - [info] Creating Vue template for 'flexdash tab' from /data/node_modules/@flexdash/node-red-flexdash/flexdash-tab.vue
3 Apr 08:06:14 - [info] Creating Vue template for 'flexdash custom' from /data/node_modules/@flexdash/node-red-flexdash/flexdash-custom.vue
03 Apr 08:06:15 - [info] RedBot version: 1.2.4 (node-red-contrib-chatbot)
```

After using the latest `process_resources.js` from repo the error was gone. CPU is still reported !=0 but I cannot tell if it is still correct.

**Comment by bartbutenaers** [comment]
@cameo69,
It might be useful if you add a comment to Paul's [issue](https://github.com/soyuka/pidusage/issues/169) that you have the same issue.  And how you run it (docker, which OS, ...).  Because perhaps you have a use case that is easier for them ro reproduce the problem...
Bart
